### ISSUE TITLE
As of Rust 1.30.0-beta.7 the primal-sieve crate hangs rustc when compiling for armv7-apple-ios

### ISSUE THREAD

**Issue by mehcode** [huonw/primal#19]
Left it running for about an hour before giving up. Just hangs on "Compiling primal-sieve ... ". I've tried various nightly versions after that (incl. most recent as of 2018-09-27). 

To be clear stable rustc compiles fine for armv7-apple-ios

**Comment by cuviper** [comment]
Thanks for filing rust-lang/rust#54627 too.  The code chunk you identified looks hairy, as generated code can be, but we should still expect the compiler to behave reasonably.

**Comment by cuviper** [comment]
The rustc issue was closed long ago, so I'm assuming this is okay now.
