### ISSUE TITLE
Documentation mismatch for primal_check::miller_rabin

### ISSUE THREAD

**Issue by wyf18** [huonw/primal#56]
Hello! 🐙
While scanning crates.io. we noticed a document-code mismatch issue in this crate, we think the doc examples are generally meant to illustrate  why someone would want to use the item.
# Location
documentation for primal_check::miller_rabin
(https://docs.rs/primal-check/0.3.3/primal_check/fn.miller_rabin.html)

# Summary
The example of the document does not mention the miller_rabin function, it is not clear how to use it.
As stated in the description, the `primal::is_prime` is faster, but we believe that the example should first illustrate the function itself.

Thank you for checking out this issue! 👍🤗

**Comment by cuviper** [comment]
It's a weird situation, but `primal::is_prime` is just a re-export of `primal_check::miller_rabin`:
https://docs.rs/primal/0.3.2/src/primal/lib.rs.html#254

And the docs make sense when viewed from that angle:
https://docs.rs/primal/0.3.2/primal/fn.is_prime.html
(but note where the "source" link takes you!)

I suppose the docs are reflecting the expectation that `primal` is the main entry point here, while `primal_check` is more of an implementation detail.

**Comment by wyf18** [comment]
Got it, so people would just use `primal::is_prime`, instead of `primal_check::miller_rabin`.
Thank you for your response!
